version: "2"
services:
  builder:
    image: amurf/sfv-builder
    build: .
    environment:
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - "$PWD/pages:/sfv/pages"
  release:
    image: amurf/sfv-builder
    command: sh -c "npm run generate && mv /sfv/dist-tmp/* /sfv/dist"
    build: .
    volumes:
      - "$PWD/pages:/sfv/pages"
      - "$PWD/dist:/sfv/dist"
